---
title: "Untitled"
author: "shuwang"
date: "2023-05-21"
output: html_document
---
```{r echo = FALSE}
library(tidyverse)
library(ggplot2)
library(plotly)


data_1 <- diamonds
data_2 <- mpg
```



```{r}
ggplot(data_1, mapping = aes(x = color)) + 
  geom_histogram(stat = "count", 
                 mapping = aes(fill = clarity), 
                 position = "dodge",
                 alpha = 0.8) + 
##(Option 1)  labs(x = "COLOR", y = "FREQUENCY", title = "HISTOGRAM OF FREQUENCY BY COLOR")
##(Option 2)   xlab("COLOR") + ylab("FREQUENCY") + ggtitle("HISTOGRAM OF FREQUENCY BY COLOR")
  labs(x = "COLOR", y = "FREQUENCY", title = "HISTOGRAM OF FREQUENCY BY COLOR") + 
  theme_bw() + 
  theme(legend.position = "bottom")


ggplot(data_2, aes(x = displ, y = hwy, color = class)) + 
  geom_point() + 
  labs(x = "Engine Displacement (L)",
       y = "Fuel Comsumption (miles/gallon)",
       title = "Fuel Economy Data") + 
  scale_color_manual(values = c("peru", "pink", "plum", "red", "black", "blue", "green"))

```